Require macOS >= 10.15 for Qt 6
With CMAKE_OSX_DEPLOYMENT_TARGET=10.14 and Qt 6.6.2:

/usr/local/include/QtCore/qfile.h:59:58: error: 'path' is unavailable:
introduced in macOS 10.15

/usr/local/include/QtCore/qfile.h:64:40: error: 'native' is unavailable:
introduced in macOS 10.15