Removal of openscad.cc cmdline section for registry change
Removal of the code block in the cmdline() section of openscad.cc that sets the Document Icon.  This was necessary due to the follow:

"This is also used from the test framework which does not link with Qt. See Travis log:
/home/travis/build/openscad/openscad/src/openscad.cc:46:16: fatal error: QDir: No such file or directory"

modified:   src/openscad.cc