Stop using + operator when creating QKeySequence
Dropped in Qt 6:

 D:/a/openscad/openscad/src/gui/MainWindow.cc:457: error: use of deleted
function 'constexpr void Qt::operator+(QFlags<Modifier>::enum_type, QFlags<Modifier>::enum_type)'