Fixed X11 linking error on Linux
output log snippet from make, before fix is applied:
```
[100%] Linking CXX executable OpenSCAD
/usr/bin/ld: CMakeFiles/OpenSCAD.dir/src/OffscreenContextGLX.cc.o: undefined reference to symbol 'XGetErrorText'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/OpenSCAD.dir/build.make:4493: recipe for target 'OpenSCAD' failed
make[2]: *** [OpenSCAD] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/OpenSCAD.dir/all' failed
make[1]: *** [CMakeFiles/OpenSCAD.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```