Fix MSVC build error: replace #warning with #pragma message
#warning is a GCC/Clang extension (standardized in C++23) and is not
supported by MSVC in C++20 mode, causing error C1021. Since this code
is inside #ifdef _MSC_VER, use #pragma message() instead.