Require macOS 10.15 for Qt 6
/usr/local/include/QtCore/qfile.h:59:58: error: 'path' is unavailable:
introduced in macOS 10.15

/usr/local/include/QtCore/qfile.h:64:40: error: 'native' is unavailable:
introduced in macOS 10.15