parser: increase parser stack depth
When parsing large generated scad files with a structure like:

    module passages() {
        color([0.5, 0.5, 0.5])
            passage(9 * dx, -5 * dy, -8 * dz, r2, 3);
        color([1, 0.5, 0.5])
            passage(7 * dx, -7 * dy, -10 * dz, r, 1)
    ...
    }

I experienced an error

    ERROR: Parser error: memory exhausted in file design.scad, line 40108

Increasing the parser stack depth solves the issue.

The same issue has been encountered before, see commit cc1f9e13534a
("quickfix: Increase parser stack depth to allow for larger designs")

Bison uses malloc() by default. The program stack size does not need to be
adjusted.

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>